### ISSUE TITLE
请求把命令改简单点，将apiocr改为图片识别

### ISSUE THREAD

**Issue by lintonxue00** [canxin121/nonebot_api_paddleocr#1]
请求把命令改简单点，将apiocr改为图片识别，使用过程中很少人知道这个命令，命令越简单用户使用频率越高

**Comment by canxin121** [comment]
好的，这个好说，我可以多添加几个命令并且可以自定义命令，这个加上api是因为和我另一个本地版相冲突
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月5日(星期三) 下午4:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [canxin121/nonebot_api_paddle] 请求把命令改简单点，将apiocr改为图片识别 (Issue #1)





 
请求把命令改简单点，将apiocr改为图片识别，使用过程中很少人知道这个命令，命令越简单用户使用频率越高

**Comment by lintonxue00** [comment]
谢谢老哥哈

**Comment by lintonxue00** [comment]
要不你写一个paddle帮助，当输入paddle帮助会给指令表，这样也简单

**Comment by canxin121** [comment]
已解决，并新增表格图转文件功能
